from .exceptions import (
    SecureExamBaseException,
    BadRequestException,
    UnauthorizedException,
    JWTExpiredException,
    JWTInvalidException,
    JWTMissingException,
    ForbiddenException,
    NotFoundException,
    UserNotFoundException,
    ExamNotFoundException,
    QuestionNotFoundException,
    DeviceNotFoundException,
    SessionNotFoundException,
    ConflictException,
    ExamAlreadySubmittedException,
    UserAlreadyExistsException,
    SessionAlreadyActiveException,
    ActivationCodeAlreadyUsedException,
    ExamStateException,
    InternalException,
    DatabaseException,
    ServiceUnavailableException,
)

from .handler import register_error_handlers

__all__ = [
    "SecureExamBaseException",
    "BadRequestException",
    "UnauthorizedException",
    "JWTExpiredException",
    "JWTInvalidException",
    "JWTMissingException",
    "ForbiddenException",
    "NotFoundException",
    "UserNotFoundException",
    "ExamNotFoundException",
    "QuestionNotFoundException",
    "DeviceNotFoundException",
    "SessionNotFoundException",
    "ConflictException",
    "ExamAlreadySubmittedException",
    "UserAlreadyExistsException",
    "SessionAlreadyActiveException",
    "ActivationCodeAlreadyUsedException",
    "ExamStateException",
    "InternalException",
    "DatabaseException",
    "ServiceUnavailableException",
    "register_error_handlers",
]